export const JOBS = [
  {
    id: 1,
    title: "Ayudante de Repostería (Part-time)",
    mype: "Pastelería Dulce Corazón",
    area: "Repostería",
    remunerated: true,
    pay: "S/ 600 al mes",
    description: "Apoyo en la preparación de masas básicas, empaquetado de pedidos y mantenimiento de limpieza en el taller de repostería. Horario flexible para estudiantes.",
    skills: ["Limpieza", "Organización", "Cocina básica"],
    schedule: "Tardes, Lunes a Viernes",
    modality: "Presencial"
  },
  {
    id: 2,
    title: "Maquetador Web HTML/CSS",
    mype: "Bodega Don Lucho",
    area: "Sistemas",
    remunerated: true,
    pay: "S/ 500 único",
    description: "Crear una plantilla web estática sencilla con el catálogo de abarrotes de la bodega. No requiere backend, solo maquetación limpia y responsiva.",
    skills: ["HTML5", "CSS3", "Diseño Web"],
    schedule: "Flexible",
    modality: "Remoto"
  },
  {
    id: 3,
    title: "Dibujante AutoCAD Junior",
    mype: "Constructora Amarilis",
    area: "Civil",
    remunerated: true,
    pay: "S/ 12 por plano",
    description: "Digitalización de bosquejos hechos a mano de viviendas unifamiliares en planos CAD de distribución y cimentación.",
    skills: ["AutoCAD", "Dibujo Técnico"],
    schedule: "Por entregables",
    modality: "Híbrido"
  },
  {
    id: 4,
    title: "Cuidador Geriátrico Domiciliario",
    mype: "Servicios de Cuidado Familiar",
    area: "Enfermería",
    remunerated: true,
    pay: "S/ 40 por turno",
    description: "Apoyo en el control de presión arterial, administración de medicamentos y acompañamiento a adulto mayor por las noches.",
    skills: ["Toma de presión", "Primeros Auxilios", "Paciencia"],
    schedule: "Noches, Fines de semana",
    modality: "Presencial"
  },
  {
    id: 5,
    title: "Auxiliar de Inventarios y Procesos",
    mype: "Almacenes El Milagro",
    area: "Industrial",
    remunerated: true,
    pay: "S/ 800 al mes",
    description: "Conteo físico de mercancías, registro en Excel e identificación de cuellos de botella en la recepción de sacos de harina.",
    skills: ["Excel básico", "Conteo físico", "Análisis de procesos"],
    schedule: "Mañanas, Lunes a Sábado",
    modality: "Presencial"
  },
  {
    id: 6,
    title: "Diseñador de Contenido para Redes",
    mype: "Cafetería Aroma de Altura",
    area: "Diseño",
    remunerated: true,
    pay: "S/ 450 al mes",
    description: "Creación de 3 publicaciones semanales y 5 historias semanales en Canva para promocionar el café de especialidad de la Mype.",
    skills: ["Canva", "Edición básica", "Creatividad"],
    schedule: "Flexible",
    modality: "Remoto"
  },
  {
    id: 7,
    title: "Asistente Administrativo Contable",
    mype: "Consultores UDH",
    area: "Administración",
    remunerated: true,
    pay: "S/ 700 al mes",
    description: "Ordenamiento de facturas, llenado de libros contables básicos y atención a llamadas de clientes corporativos.",
    skills: ["Orden", "Facturación", "Atención al cliente"],
    schedule: "Tardes",
    modality: "Presencial"
  },
  {
    id: 8,
    title: "Ayudante en Peluquería Canina",
    mype: "Petto Veterinarios",
    area: "Veterinaria",
    remunerated: true,
    pay: "S/ 15 por baño",
    description: "Baño, secado y cepillado de mascotas. Sujeción segura de perros durante el corte de pelo profesional.",
    skills: ["Amor por animales", "Fuerza física", "Paciencia"],
    schedule: "Fines de semana",
    modality: "Presencial"
  },
  {
    id: 9,
    title: "Tutor de Matemáticas de Primaria",
    mype: "Refuerzo Escolar Huánuco",
    area: "Educación",
    remunerated: true,
    pay: "S/ 20 por hora",
    description: "Clases de nivelación presenciales a domicilio para niños de primaria con dificultades en álgebra y geometría básica.",
    skills: ["Pedagogía", "Matemáticas", "Paciencia"],
    schedule: "Tardes, flexible",
    modality: "Presencial"
  },
  {
    id: 10,
    title: "Decorador de Tortas y Bocaditos",
    mype: "Pastelería Arte y Sabor",
    area: "Repostería",
    remunerated: true,
    pay: "S/ 350 por evento",
    description: "Preparación de glaseados, cremas de mantequilla y decoración creativa de cupcakes y tortas temáticas los viernes por la tarde.",
    skills: ["Decoración", "Precisión", "Creatividad"],
    schedule: "Fines de semana",
    modality: "Presencial"
  },
  {
    id: 11,
    title: "Instalador de Software y Antivirus",
    mype: "Servicio Técnico Wilson",
    area: "Sistemas",
    remunerated: true,
    pay: "S/ 25 por equipo",
    description: "Formateo de computadoras, instalación de sistemas operativos, paquetes de ofimática y limpieza física de laptops.",
    skills: ["Hardware", "Sistemas Operativos", "Diagnóstico"],
    schedule: "Flexible",
    modality: "Presencial"
  },
  {
    id: 12,
    title: "Control de Calidad de Lotes",
    mype: "Fábrica de Fideos San Felipe",
    area: "Industrial",
    remunerated: true,
    pay: "S/ 850 al mes",
    description: "Monitoreo del peso de los empaques de fideos y reporte de variaciones fuera del rango aceptado por el control de calidad.",
    skills: ["Medición", "Atención al detalle", "Reportes"],
    schedule: "Tardes, Lunes a Sábado",
    modality: "Presencial"
  },
  {
    id: 13,
    title: "Asistente de Campaña de Vacunación",
    mype: "Policlínico Central",
    area: "Enfermería",
    remunerated: false,
    pay: "Ad Honorem (Certificado)",
    description: "Apoyo en el registro de pacientes, llenado de fichas de vacunación y toma inicial de temperatura en campañas locales.",
    skills: ["Empatía", "Llenado de fichas", "Organización"],
    schedule: "Fines de semana",
    modality: "Presencial"
  },
  {
    id: 14,
    title: "Asistente de Presupuestos de Obra",
    mype: "Ingenieros Civiles Consultores",
    area: "Civil",
    remunerated: true,
    pay: "S/ 500 por expediente",
    description: "Metrados de concreto, encofrado y acero en planos de viviendas de baja densidad para generar los expedientes técnicos de cotización.",
    skills: ["Metrados", "Planos", "Excel"],
    schedule: "Por entregables",
    modality: "Remoto"
  },
  {
    id: 15,
    title: "Paseador de Perros de Zona Residencial",
    mype: "Club Canino Huánuco",
    area: "Veterinaria",
    remunerated: true,
    pay: "S/ 10 por perro / hora",
    description: "Pasear grupos pequeños de perros de razas medianas en parques locales garantizando su seguridad e hidratación.",
    skills: ["Control canino", "Responsabilidad"],
    schedule: "Mañanas",
    modality: "Presencial"
  },
  {
    id: 16,
    title: "Fotógrafo de Catálogo para E-commerce",
    mype: "Boutique Glamour",
    area: "Diseño",
    remunerated: true,
    pay: "S/ 300 por sesión",
    description: "Fotografiar 30 prendas de vestir en fondo blanco con iluminación adecuada para subir las imágenes a tienda en línea.",
    skills: ["Fotografía", "Edición de Fotos"],
    schedule: "Fines de semana",
    modality: "Presencial"
  },
  {
    id: 17,
    title: "Promotor de Ventas en Tienda",
    mype: "Tecnología y Más",
    area: "Administración",
    remunerated: true,
    pay: "S/ 600 al mes + comisiones",
    description: "Atención a clientes interesados en adquirir accesorios móviles, cargadores y micas protectoras en módulo comercial.",
    skills: ["Facilidad de palabra", "Ventas", "Caja"],
    schedule: "Tardes",
    modality: "Presencial"
  },
  {
    id: 18,
    title: "Redactor de Contenidos Académicos",
    mype: "Centro Preuniversitario Exitus",
    area: "Educación",
    remunerated: true,
    pay: "S/ 300 por módulo",
    description: "Redacción y maquetación de ejercicios resueltos de Razonamiento Matemático para compendios académicos.",
    skills: ["Redacción", "LaTeX o Word", "Matemáticas"],
    schedule: "Por entregables",
    modality: "Remoto"
  },
  {
    id: 19,
    title: "Ayudante de Repostería y Panificación",
    mype: "Pastelería Santa María",
    area: "Repostería",
    remunerated: true,
    pay: "S/ 550 al mes",
    description: "Ayuda en el porcionamiento de panes, pesado de insumos de repostería y limpieza general al cierre del horno.",
    skills: ["Fuerza física", "Higiene", "Orden"],
    schedule: "Mañanas, Lunes a Viernes",
    modality: "Presencial"
  },
  {
    id: 20,
    title: "Creador de Landing Pages (React)",
    mype: "Consultoría de Software Huánuco",
    area: "Sistemas",
    remunerated: true,
    pay: "S/ 700 único",
    description: "Desarrollar una landing page moderna con formulario de contacto utilizando React y CSS para una empresa de seguridad física local.",
    skills: ["React", "CSS Grid", "Forms"],
    schedule: "Flexible",
    modality: "Remoto"
  },
  {
    id: 21,
    title: "Auxiliar en Salud Ocupacional",
    mype: "Clínica de la Solidaridad",
    area: "Enfermería",
    remunerated: true,
    pay: "S/ 900 al mes",
    description: "Apoyo en el archivado de fichas de salud ocupacional de trabajadores locales y toma inicial de peso y talla.",
    skills: ["Toma de signos vitales", "Archivado"],
    schedule: "Part-time",
    modality: "Presencial"
  },
  {
    id: 22,
    title: "Digitalizador de Planos Catastrales",
    mype: "Consultora Territorial SAC",
    area: "Civil",
    remunerated: true,
    pay: "S/ 8 por plano digitalizado",
    description: "Importar mapas e imágenes satelitales en AutoCAD para delinear parcelas agrícolas e ingresar coordenadas UTM básicas.",
    skills: ["AutoCAD", "Coordenadas UTM"],
    schedule: "Flexible",
    modality: "Remoto"
  },
  {
    id: 23,
    title: "Trazador de Procesos de Ensamblaje",
    mype: "Metalmecánica El Inka",
    area: "Industrial",
    remunerated: true,
    pay: "S/ 400 único",
    description: "Diagramar en Visio los flujos de ensamble de estructuras metálicas para documentar los pasos de manufactura.",
    skills: ["Flujogramas", "Microsoft Visio", "Ingeniería de métodos"],
    schedule: "Flexible",
    modality: "Híbrido"
  },
  {
    id: 24,
    title: "Ilustrador de Cuentos Infantiles",
    mype: "Editorial Sol de Huánuco",
    area: "Diseño",
    remunerated: true,
    pay: "S/ 50 por ilustración",
    description: "Crear ilustraciones digitales infantiles a color para libro de fábulas regionales. Estilo artístico libre.",
    skills: ["Ilustración digital", "Creatividad"],
    schedule: "Por entregables",
    modality: "Remoto"
  },
  {
    id: 25,
    title: "Administrador de Base de Datos Junior",
    mype: "Distribuidora de Alimentos Huánuco",
    area: "Sistemas",
    remunerated: true,
    pay: "S/ 750 al mes",
    description: "Apoyo en la creación de tablas, triggers básicos y optimización de consultas SQL en base de datos MySQL local de ventas.",
    skills: ["SQL", "MySQL", "Esquemas de BD"],
    schedule: "Part-time, Remoto",
    modality: "Remoto"
  },
  {
    id: 26,
    title: "Auxiliar Veterinario de Campo",
    mype: "Veterinaria Ganadera",
    area: "Veterinaria",
    remunerated: true,
    pay: "S/ 70 por salida de campo",
    description: "Asistencia al veterinario principal en la sujeción de vacas e inyección de vitaminas en hatos de la zona periférica.",
    skills: ["Trato de animales mayores", "Resistencia física"],
    schedule: "Fines de semana",
    modality: "Presencial"
  },
  {
    id: 27,
    title: "Cajero para Tienda de Abarrotes",
    mype: "Supermercado El Sol",
    area: "Administración",
    remunerated: true,
    pay: "S/ 650 al mes",
    description: "Registro de productos en la caja registradora, cobro con POS o efectivo, arqueo diario e inventariado final al cierre.",
    skills: ["Caja", "POS", "Orden"],
    schedule: "Noches, Lunes a Sábado",
    modality: "Presencial"
  },
  {
    id: 28,
    title: "Asistente de Redacción para Web",
    mype: "Diario Regional Huánuco",
    area: "Educación",
    remunerated: true,
    pay: "S/ 400 al mes",
    description: "Corrección ortográfica y de estilo en notas locales enviadas por periodistas antes de ser publicadas en el sitio web.",
    skills: ["Ortografía", "Redacción", "WordPress básico"],
    schedule: "Tardes",
    modality: "Remoto"
  },
  {
    id: 29,
    title: "Ayudante de Cocina y Sandwichería",
    mype: "Cafetería La Parada",
    area: "Repostería",
    remunerated: true,
    pay: "S/ 500 al mes",
    description: "Preparación rápida de jugos, sándwiches, ensaladas y lavado de vajillas durante la hora del desayuno y almuerzo.",
    skills: ["Rapidez", "Higiene", "Cocina básica"],
    schedule: "Mañanas",
    modality: "Presencial"
  },
  {
    id: 30,
    title: "Tester de Aplicaciones Web",
    mype: "Desarrollos Locales SAC",
    area: "Sistemas",
    remunerated: true,
    pay: "S/ 450 al mes",
    description: "Pruebas de clic, registro de fallas ortográficas y errores de diseño en proyectos web creados para clientes locales de la consultora.",
    skills: ["Atención al detalle", "Reporte de Bugs"],
    schedule: "Flexible",
    modality: "Remoto"
  },
  {
    id: 31,
    title: "Cuidado de Mascotas a Domicilio",
    mype: "Servicio Cuidador Express",
    area: "Veterinaria",
    remunerated: true,
    pay: "S/ 25 por día",
    description: "Alimentar, limpiar caja de arena y pasar tiempo con gatos de clientes que viajan por fines de semana largos.",
    skills: ["Trato de gatos", "Responsabilidad"],
    schedule: "Fines de semana",
    modality: "Presencial"
  },
  {
    id: 32,
    title: "Asistente de Laboratorio Geriátrico",
    mype: "Laboratorio Médico Andino",
    area: "Enfermería",
    remunerated: true,
    pay: "S/ 800 al mes",
    description: "Limpieza y desinfección de tubos de ensayo, organización de reactivos y apoyo en toma de temperatura e historial a pacientes.",
    skills: ["Limpieza clínica", "Toma de datos"],
    schedule: "Tardes",
    modality: "Presencial"
  },
  {
    id: 33,
    title: "Asistente de Levantamiento de Campo",
    mype: "Topógrafos Asociados Huánuco",
    area: "Civil",
    remunerated: true,
    pay: "S/ 50 por día",
    description: "Carga del teodolito y prisma de medición, colocación de estacas y apoyo físico durante el levantamiento topográfico de terrenos.",
    skills: ["Soporte de equipos", "Resistencia física"],
    schedule: "Fines de semana",
    modality: "Presencial"
  },
  {
    id: 34,
    title: "Rediseño de Catálogo en PDF",
    mype: "Ferretería El Tornillo",
    area: "Diseño",
    remunerated: true,
    pay: "S/ 200 único",
    description: "Rediseñar un catálogo físico antiguo de herramientas de 10 páginas a un formato PDF digital moderno utilizando Photoshop o Illustrator.",
    skills: ["Photoshop", "Diseño de Catálogo"],
    schedule: "Flexible",
    modality: "Remoto"
  },
  {
    id: 35,
    title: "Auxiliar de Almacenamiento y Logística",
    mype: "Distribuidora El Progreso",
    area: "Industrial",
    remunerated: true,
    pay: "S/ 900 al mes",
    description: "Carga de cajas al inventario, clasificación por código de barras y apoyo en el etiquetado del stock ingresado.",
    skills: ["Carga física", "Atención al detalle", "Orden"],
    schedule: "Mañanas",
    modality: "Presencial"
  },
  {
    id: 36,
    title: "Asistente Contable Junior",
    mype: "Contadores y Auditores Asociados",
    area: "Administración",
    remunerated: true,
    pay: "S/ 700 al mes",
    description: "Elaboración de conciliaciones bancarias básicas y archivo mensual de comprobantes de pago impresos y digitales.",
    skills: ["Conciliación bancaria", "Excel"],
    schedule: "Tardes",
    modality: "Presencial"
  },
  {
    id: 37,
    title: "Tutor de Idioma Inglés Técnico",
    mype: "Centro Cultural de Idiomas",
    area: "Educación",
    remunerated: true,
    pay: "S/ 25 por hora",
    description: "Guiar sesiones de conversación grupales en inglés para estudiantes universitarios de ingeniería.",
    skills: ["Inglés fluido", "Dinámica grupal"],
    schedule: "Sábados mañanas",
    modality: "Presencial"
  },
  {
    id: 38,
    title: "Decorador de Bocaditos Dulces",
    mype: "Candy Bar Dulzuras",
    area: "Repostería",
    remunerated: true,
    pay: "S/ 250 por fin de semana",
    description: "Decoración fina de bombones de chocolate, armado de fuentes de dulces y decoración de mesas temáticas para cumpleaños.",
    skills: ["Creatividad", "Paciencia", "Estética"],
    schedule: "Fines de semana",
    modality: "Presencial"
  },
  {
    id: 39,
    title: "Programador de Bot WhatsApp simple",
    mype: "Clínica Veterinaria Mascotas",
    area: "Sistemas",
    remunerated: true,
    pay: "S/ 600 único",
    description: "Implementar un flujo simple en Node.js para responder preguntas frecuentes y dar el número de teléfono mediante la API de WhatsApp.",
    skills: ["Node.js", "API Integrations", "Chatbots"],
    schedule: "Flexible",
    modality: "Remoto"
  },
  {
    id: 40,
    title: "Auxiliar en Terapia Física",
    mype: "Centro Kinesiología Andino",
    area: "Enfermería",
    remunerated: true,
    pay: "S/ 650 al mes",
    description: "Apoyo al tecnólogo médico en la preparación de las camillas de masaje, colocación de compresas calientes e insumos clínicos.",
    skills: ["Atención médica inicial", "Limpieza"],
    schedule: "Tardes",
    modality: "Presencial"
  },
  {
    id: 41,
    title: "Ayudante de Mediciones Catastrales",
    mype: "Consultora de Ingeniería Civil",
    area: "Civil",
    remunerated: true,
    pay: "S/ 45 por día",
    description: "Tendido de huinchas metálicas de 50 metros y colocación de hitos de concreto demarcatorios de linderos en terrenos rústicos.",
    skills: ["Medición física", "Trabajo rústico"],
    schedule: "Fines de semana",
    modality: "Presencial"
  },
  {
    id: 42,
    title: "Asistente de Envasado y Empaque",
    mype: "Fábrica de Conservas Huánuco",
    area: "Industrial",
    remunerated: true,
    pay: "S/ 800 al mes",
    description: "Supervisar el sellado correcto de latas de conservas de fruta y colocación de etiquetas impresas antes del encajonado.",
    skills: ["Velocidad de manos", "Orden"],
    schedule: "Mañanas",
    modality: "Presencial"
  },
  {
    id: 43,
    title: "Diseñador de Logotipos para Mype",
    mype: "Bodega La Económica",
    area: "Diseño",
    remunerated: true,
    pay: "S/ 150 único",
    description: "Diseño de un logotipo moderno y su variante circular en vector para impresión de bolsas plásticas y letrero comercial.",
    skills: ["Adobe Illustrator", "Branding"],
    schedule: "Flexible",
    modality: "Remoto"
  },
  {
    id: 44,
    title: "Auxiliar de Archivo y Digitalización",
    mype: "Estudio Jurídico Lora & Asociados",
    area: "Administración",
    remunerated: true,
    pay: "S/ 600 al mes",
    description: "Escaneo de expedientes judiciales impresos, conversión a formato PDF ordenado y nombramiento según código interno.",
    skills: ["Escaneo", "Orden de Archivos", "Excel"],
    schedule: "Tardes",
    modality: "Presencial"
  },
  {
    id: 45,
    title: "Cuidador de Albergue Temporal",
    mype: "Refugio Patitas Unidas",
    area: "Veterinaria",
    remunerated: false,
    pay: "Ad Honorem (Certificado)",
    description: "Alimentar caniles, limpieza de jaulas, cepillado de pelaje y apoyo en paseos diarios de perros rescatados.",
    skills: ["Cariño por animales", "Fuerza física"],
    schedule: "Fines de semana",
    modality: "Presencial"
  },
  {
    id: 46,
    title: "Tutor de Química Preuniversitaria",
    mype: "Academia Bryce Huánuco",
    area: "Educación",
    remunerated: true,
    pay: "S/ 22 por hora",
    description: "Dictado de seminarios cortos de química inorgánica y balance de ecuaciones para postulantes a carreras de salud.",
    skills: ["Química", "Pedagogía"],
    schedule: "Sábados tarde",
    modality: "Presencial"
  },
  {
    id: 47,
    title: "Decorador y Glaseador de Galletas",
    mype: "Pastelería Sweet Cookies",
    area: "Repostería",
    remunerated: true,
    pay: "S/ 300 al mes",
    description: "Decoración artística con manga pastelera y glasa real sobre galletas temáticas navideñas e infantiles.",
    skills: ["Manga pastelera", "Pulso fino"],
    schedule: "Part-time flexible",
    modality: "Presencial"
  },
  {
    id: 48,
    title: "Administrador de Redes Sociales",
    mype: "Veterinaria San José",
    area: "Sistemas",
    remunerated: true,
    pay: "S/ 400 al mes",
    description: "Programación de posts en Facebook e Instagram, y respuesta inmediata a mensajes directos de clientes agendando citas básicas.",
    skills: ["Redes Sociales", "Atención digital"],
    schedule: "Part-time, Remoto",
    modality: "Remoto"
  },
  {
    id: 49,
    title: "Asistente de Inyecciones a Domicilio",
    mype: "Servicio Enfermería Express",
    area: "Enfermería",
    remunerated: true,
    pay: "S/ 15 por inyección aplicada",
    description: "Colocación de inyectables intramusculares a pacientes locales con receta médica comprobada. Requiere implementos propios.",
    skills: ["Inyectables", "Bioseguridad"],
    schedule: "Turnos rotativos",
    modality: "Presencial"
  },
  {
    id: 50,
    title: "Asistente de Diseñador en AutoCAD",
    mype: "Constructora Amarilis SAC",
    area: "Civil",
    remunerated: true,
    pay: "S/ 600 al mes",
    description: "Modificación de planos arquitectónicos existentes bajo la supervisión directa del ingeniero residente de obra.",
    skills: ["AutoCAD", "Modificación de planos"],
    schedule: "Tardes",
    modality: "Presencial"
  },
  {
    id: 51,
    title: "Cronometrador de Procesos de Fábrica",
    mype: "Textiles Andinos",
    area: "Industrial",
    remunerated: true,
    pay: "S/ 450 por medición",
    description: "Medir los tiempos de confección de 10 operarios de costura para identificar mermas de tiempo en la planta.",
    skills: ["Cronometraje", "Excel", "Ingeniería de métodos"],
    schedule: "Flexible",
    modality: "Presencial"
  },
  {
    id: 52,
    title: "Ilustrador Vectorial para Polos",
    mype: "Confecciones T-Shirt Art",
    area: "Diseño",
    remunerated: true,
    pay: "S/ 35 por diseño aprobado",
    description: "Crear vectores de cultura pop y anime en formato EPS e Illustrator listos para el proceso de serigrafía en polos.",
    skills: ["Ilustrator", "Vectores", "Creatividad"],
    schedule: "Flexible",
    modality: "Remoto"
  },
  {
    id: 53,
    title: "Archivero e Inventariador Físico",
    mype: "Botica Farmacia Andina",
    area: "Administración",
    remunerated: true,
    pay: "S/ 550 al mes",
    description: "Registro manual del stock de medicamentos en los anaqueles y cotejo con el inventario del sistema interno.",
    skills: ["Orden", "Conteo de Stock", "Concentración"],
    schedule: "Noches",
    modality: "Presencial"
  },
  {
    id: 54,
    title: "Ayudante en Granja y Cuidado Animal",
    mype: "Finca El Porvenir",
    area: "Veterinaria",
    remunerated: true,
    pay: "S/ 70 por fin de semana",
    description: "Limpieza de corrales de porcinos, llenado de comederos y apoyo en el pesado mensual de lechones en la granja.",
    skills: ["Fuerza física", "Cuidado animal"],
    schedule: "Fines de semana",
    modality: "Presencial"
  },
  {
    id: 55,
    title: "Tutor de Álgebra y Trigonometría",
    mype: "Refuerzo Escolar Elite",
    area: "Educación",
    remunerated: true,
    pay: "S/ 20 por hora",
    description: "Dictar clases de nivelación presenciales a estudiantes que cursan 4to y 5to de secundaria en colegios estatales.",
    skills: ["Álgebra", "Pedagogía"],
    schedule: "Tardes",
    modality: "Presencial"
  },
  {
    id: 56,
    title: "Ayudante de Panadería (Turno Madrugada)",
    mype: "Panadería Don Lucho",
    area: "Repostería",
    remunerated: true,
    pay: "S/ 700 al mes",
    description: "Apoyo en el boleado de masa de pan, colocación de bandejas en el horno y embolsado inicial de panes.",
    skills: ["Resistencia física", "Madrugador", "Rapidez"],
    schedule: "Madrugadas, Lunes a Sábado",
    modality: "Presencial"
  },
  {
    id: 57,
    title: "Programador Web Frontend Junior (Vite)",
    mype: "Consultoría de Software Huánuco",
    area: "Sistemas",
    remunerated: true,
    pay: "S/ 800 al mes",
    description: "Desarrollar vistas en React utilizando layouts sencillos y consumir APIs JSON de prueba provistas por la consultora.",
    skills: ["React", "CSS", "Vite"],
    schedule: "Part-time, Remoto",
    modality: "Remoto"
  },
  {
    id: 58,
    title: "Apoyo en Toma de Presión y Signos",
    mype: "Campañas de Salud Regional",
    area: "Enfermería",
    remunerated: false,
    pay: "Ad Honorem (Certificado)",
    description: "Medición rápida de temperatura corporal, toma de presión e hidratación a participantes en ferias deportivas locales.",
    skills: ["Toma de Signos Vitales", "Primeros Auxilios"],
    schedule: "Sábados mañana",
    modality: "Presencial"
  },
  {
    id: 59,
    title: "Metrador de Estructuras Básicas",
    mype: "Estudio Ingeniería y Construcción",
    area: "Civil",
    remunerated: true,
    pay: "S/ 10 por plano analizado",
    description: "Metrados en base a planos impresos para calcular volúmenes de concreto y metros cuadrados de encofrado de zapatas.",
    skills: ["Metrados de obra", "Excel"],
    schedule: "Flexible",
    modality: "Presencial"
  },
  {
    id: 60,
    title: "Clasificador de Insumos Industriales",
    mype: "Ensamblajes del Centro",
    area: "Industrial",
    remunerated: true,
    pay: "S/ 600 al mes",
    description: "Recibir cajas de tornillos, pernos y remaches, clasificarlos en los gaveteros por medida exacta e ingresar datos en sistema.",
    skills: ["Precisión", "Uso de calibres", "Orden"],
    schedule: "Tardes",
    modality: "Presencial"
  },
  {
    id: 61,
    title: "Retocador Digital de Joyas",
    mype: "Joyería Platería Fina",
    area: "Diseño",
    remunerated: true,
    pay: "S/ 15 por foto limpia",
    description: "Quitar reflejos y polvo en fotografías tomadas a anillos y pulseras de plata usando pinceles de clonación en Photoshop.",
    skills: ["Adobe Photoshop", "Retoque fotográfico"],
    schedule: "Por entregables",
    modality: "Remoto"
  },
  {
    id: 62,
    title: "Promotor de Telefonía Móvil",
    mype: "Distribuidora Celular Huánuco",
    area: "Administración",
    remunerated: true,
    pay: "S/ 500 al mes + comisiones",
    description: "Ofrecer chips móviles y planes de portabilidad a peatones en el centro comercial de la ciudad.",
    skills: ["Persuasión", "Ventas directas"],
    schedule: "Tardes",
    modality: "Presencial"
  },
  {
    id: 63,
    title: "Tutor de Gramática y Ortografía",
    mype: "Refuerzo Escolar Huánuco",
    area: "Educación",
    remunerated: true,
    pay: "S/ 18 por hora",
    description: "Regularizar en ortografía, tildación y redacción de textos a niños de 5to y 6to de primaria.",
    skills: ["Pedagogía infantil", "Redacción"],
    schedule: "Tardes, flexible",
    modality: "Presencial"
  },
  {
    id: 64,
    title: "Ayudante en Pastelería Artesanal",
    mype: "Taller Dulce Repostería",
    area: "Repostería",
    remunerated: true,
    pay: "S/ 400 al mes",
    description: "Ayudar en la preparación de almíbares, cremas pasteleras y empaquetado de cajas de alfajores los sábados por la tarde.",
    skills: ["Cocina básica", "Higiene"],
    schedule: "Sábados tarde",
    modality: "Presencial"
  },
  {
    id: 65,
    title: "Desarrollador de Sitio Web Simple (Astro)",
    mype: "Estudio Jurídico Lora & Asociados",
    area: "Sistemas",
    remunerated: true,
    pay: "S/ 700 único",
    description: "Desarrollar un sitio web informativo rápido con Astro.js que muestre la misión, visión y áreas legales del estudio jurídico.",
    skills: ["Astro.js", "CSS3", "HTML5"],
    schedule: "Flexible",
    modality: "Remoto"
  },
  {
    id: 66,
    title: "Enfermera de Guardia Nocturna (Botica)",
    mype: "FarmaSalud Amarilis",
    area: "Enfermería",
    remunerated: true,
    pay: "S/ 50 por turno de noche",
    description: "Permanecer en la farmacia para toma de signos vitales, inyección de ampollas y orientación básica de salud a clientes.",
    skills: ["Inyectables", "Trato cordial"],
    schedule: "Noches rotativas",
    modality: "Presencial"
  },
  {
    id: 67,
    title: "Dibujante Técnico Estructural CAD",
    mype: "Constructora e Inversiones SAC",
    area: "Civil",
    remunerated: true,
    pay: "S/ 12 por plano estructural",
    description: "Digitalización de planos de vigas y columnas de cimentación a partir de esquemas proporcionados por el ingeniero calculista.",
    skills: ["AutoCAD", "Dibujo de estructuras"],
    schedule: "Flexible",
    modality: "Remoto"
  },
  {
    id: 68,
    title: "Optimizador de Procesos de Almacén",
    mype: "Bodega Mayorista El Trébol",
    area: "Industrial",
    remunerated: true,
    pay: "S/ 650 al mes",
    description: "Ordenar las estanterías según rotación FIFO (Primero en Entrar, Primero en Salir) de sacos de arroz e insumos secos.",
    skills: ["Clasificación FIFO", "Organización física"],
    schedule: "Mañanas",
    modality: "Presencial"
  },
  {
    id: 69,
    title: "Diseñador de Flyers para Eventos",
    mype: "Discoteca La Parada Club",
    area: "Diseño",
    remunerated: true,
    pay: "S/ 25 por flyer publicitario",
    description: "Diseño digital llamativo de flyers en alta definición para promocionar los eventos y ofertas de bebidas de cada fin de semana.",
    skills: ["Photoshop", "Diseño gráfico", "Estética moderna"],
    schedule: "Flexible",
    modality: "Remoto"
  },
  {
    id: 70,
    title: "Asistente de Ventas y Presupuestos",
    mype: "Ferretería El Tornillo",
    area: "Administración",
    remunerated: true,
    pay: "S/ 550 al mes",
    description: "Atender a clientes de mostrador, cotizar listas de materiales de construcción y reportar ventas diarias.",
    skills: ["Ventas", "Caja", "Atención al cliente"],
    schedule: "Tardes",
    modality: "Presencial"
  },
  {
    id: 71,
    title: "Paseador de Perros (Turno Tarde)",
    mype: "Club Canino Huánuco",
    area: "Veterinaria",
    remunerated: true,
    pay: "S/ 8 por perro / hora",
    description: "Paseos de socialización controlada de perros medianos por las tardes en parques seguros y áreas verdes locales.",
    skills: ["Cuidado canino", "Responsabilidad"],
    schedule: "Tardes",
    modality: "Presencial"
  },
  {
    id: 72,
    title: "Tutor de Física Preuniversitaria",
    mype: "Academia Bryce",
    area: "Educación",
    remunerated: true,
    pay: "S/ 20 por hora",
    description: "Dictado de clases prácticas presenciales de física preuniversitaria (Estática, Cinemática y Dinámica) los sábados tarde.",
    skills: ["Física", "Explicación clara"],
    schedule: "Sábados tarde",
    modality: "Presencial"
  },
  {
    id: 73,
    title: "Decorador de Cupcakes Creativos",
    mype: "Pastelería Sweet Cookies",
    area: "Repostería",
    remunerated: true,
    pay: "S/ 150 por sesión",
    description: "Preparación de coberturas temáticas en masa elástica o crema de mantequilla para empaques de regalo de cupcakes corporativos.",
    skills: ["Modelado en fondant", "Creatividad"],
    schedule: "Flexible",
    modality: "Presencial"
  },
  {
    id: 74,
    title: "Mantenimiento Preventivo de PCs",
    mype: "Servicio Técnico Wilson",
    area: "Sistemas",
    remunerated: true,
    pay: "S/ 30 por PC limpia",
    description: "Sopleteado de polvo interno, aplicación de pasta térmica, limpieza de ventiladores y ensamblaje de componentes en gabinetes.",
    skills: ["Hardware", "Ensamblaje", "Limpieza de circuitos"],
    schedule: "Flexible",
    modality: "Presencial"
  },
  {
    id: 75,
    title: "Auxiliar en Campañas Médicas UDH",
    mype: "Campañas Médicas UDH",
    area: "Enfermería",
    remunerated: false,
    pay: "Ad Honorem (Certificado)",
    description: "Apoyo en el control de fila de pacientes y entrega de volantes de prevención e hidratación durante la feria médica regional.",
    skills: ["Trato humano", "Organización"],
    schedule: "Sábados mañana",
    modality: "Presencial"
  },
  {
    id: 76,
    title: "Cubicador de Materiales de Obra",
    mype: "Constructora e Inversiones",
    area: "Civil",
    remunerated: true,
    pay: "S/ 450 por proyecto",
    description: "Calcular volúmenes de concreto y número de ladrillos requeridos para la edificación de muros de contención sencillos.",
    skills: ["Metrados de obra", "Lectura de planos"],
    schedule: "Flexible",
    modality: "Remoto"
  },
  {
    id: 77,
    title: "Auxiliar de Control de Inventario",
    mype: "Textiles Andinos",
    area: "Industrial",
    remunerated: true,
    pay: "S/ 600 al mes",
    description: "Registrar la salida de rollos de tela y avíos mediante hojas de inventario físico y posterior digitalización en Excel.",
    skills: ["Excel", "Conteo de insumos"],
    schedule: "Tardes",
    modality: "Presencial"
  },
  {
    id: 78,
    title: "Dibujante Vectorial para Vinilos",
    mype: "Imprenta Diseños Locales",
    area: "Diseño",
    remunerated: true,
    pay: "S/ 120 por pack de diseños",
    description: "Trazar logos comerciales existentes en formato vector de alta resolución para corte en plotter de vinilo adhesivo.",
    skills: ["Adobe Illustrator", "Trazado pluma"],
    schedule: "Flexible",
    modality: "Remoto"
  },
  {
    id: 79,
    title: "Auxiliar de Archivador e Inventario",
    mype: "Botica Farmacia Andina",
    area: "Administración",
    remunerated: true,
    pay: "S/ 500 al mes",
    description: "Archivado físico de facturas y notas de despacho de medicamentos, así como conteo de lotes vencidos en stock.",
    skills: ["Orden", "Clasificación por fechas"],
    schedule: "Noches",
    modality: "Presencial"
  },
  {
    id: 80,
    title: "Ayudante en Clinica Veterinaria",
    mype: "Refugio Patitas Unidas",
    area: "Veterinaria",
    remunerated: false,
    pay: "Ad Honorem (Certificado)",
    description: "Limpieza de las jaulas de internamiento de perros y gatos, preparación de gasas clínicas y sujeción de mascotas para inyectables.",
    skills: ["Trato animal", "Limpieza de instrumental"],
    schedule: "Fines de semana",
    modality: "Presencial"
  },
  {
    id: 81,
    title: "Ayudante de Repostería (Fines de semana)",
    mype: "Pastelería Dulce Corazón",
    area: "Repostería",
    remunerated: true,
    pay: "S/ 250 al mes",
    description: "Apoyo en el horneado de queques, limpieza de moldes y preparación de merengue los sábados y domingos en las mañanas.",
    skills: ["Limpieza", "Orden", "Higiene"],
    schedule: "Fines de semana",
    modality: "Presencial"
  },
  {
    id: 82,
    title: "Desarrollador Web Front-end (React + CSS)",
    mype: "Bodega Mayorista El Trébol",
    area: "Sistemas",
    remunerated: true,
    pay: "S/ 600 único",
    description: "Crear una maqueta web autogestionada responsiva en React con buscador interno para que la bodega muestre sus precios diarios.",
    skills: ["React", "CSS Grid", "JS Filters"],
    schedule: "Flexible",
    modality: "Remoto"
  },
  {
    id: 83,
    title: "Auxiliar en Terapia Física",
    mype: "Centro Kinesiología Andino",
    area: "Enfermería",
    remunerated: true,
    pay: "S/ 700 al mes",
    description: "Apoyo al terapeuta en el encendido de equipos, colocación de parches de electroterapia y desinfección de colchonetas de camillas.",
    skills: ["Atención médica inicial", "Higiene"],
    schedule: "Tardes",
    modality: "Presencial"
  },
  {
    id: 84,
    title: "Ayudante de Mediciones Catastrales",
    mype: "Consultora de Ingeniería Civil",
    area: "Civil",
    remunerated: true,
    pay: "S/ 40 por salida de campo",
    description: "Trazado físico de linderos rústicos con estacas de madera y yeso blanco en parcelas rurales de la zona.",
    skills: ["Trabajo de campo", "Estacas de madera"],
    schedule: "Fines de semana",
    modality: "Presencial"
  },
  {
    id: 85,
    title: "Cronometrador de Tiempos de Confección",
    mype: "Confecciones T-Shirt Art",
    area: "Industrial",
    remunerated: true,
    pay: "S/ 400 por medición",
    description: "Cronometrar las operaciones de costura y empaque de prendas en el taller textil para generar la base de tiempos estándar.",
    skills: ["Cronometraje", "Excel básico"],
    schedule: "Flexible",
    modality: "Presencial"
  },
  {
    id: 86,
    title: "Retocador Digital de Fotos de Ropa",
    mype: "Boutique Glamour",
    area: "Diseño",
    remunerated: true,
    pay: "S/ 10 por imagen editada",
    description: "Ajuste de color, contraste y corrección de arrugas en fotografías de catálogo de prendas de vestir para redes sociales.",
    skills: ["Photoshop", "Filtros de color"],
    schedule: "Flexible",
    modality: "Remoto"
  },
  {
    id: 87,
    title: "Asistente de Presupuestos de Obra",
    mype: "Consultora Territorial SAC",
    area: "Civil",
    remunerated: true,
    pay: "S/ 550 por expediente técnico",
    description: "Elaboración de tablas de metrados de concreto y encofrado a partir de planos CAD digitales para cotizar expedientes.",
    skills: ["Metrados de obra", "AutoCAD", "Excel"],
    schedule: "Flexible",
    modality: "Remoto"
  },
  {
    id: 88,
    title: "Auxiliar de Almacenamiento y Conteo",
    mype: "Almacenes El Milagro",
    area: "Industrial",
    remunerated: true,
    pay: "S/ 600 al mes",
    description: "Clasificación de lotes de insumos secos entrantes, pesado de bolsas de granos y reporte escrito al jefe de almacén.",
    skills: ["Conteo físico", "Clasificación de lotes"],
    schedule: "Tardes",
    modality: "Presencial"
  },
  {
    id: 89,
    title: "Asistente de Diseñador Gráfico",
    mype: "Imprenta Diseños Locales",
    area: "Diseño",
    remunerated: true,
    pay: "S/ 650 al mes",
    description: "Apoyo en el maquetado de tarjetas personales, flyers informativos y banners publicitarios para clientes de la imprenta.",
    skills: ["CorelDraw o Illustrator", "Diseño publicitario"],
    schedule: "Tardes",
    modality: "Presencial"
  },
  {
    id: 90,
    title: "Asistente Contable Part-time",
    mype: "Contadores y Auditores Asociados",
    area: "Administración",
    remunerated: true,
    pay: "S/ 700 al mes",
    description: "Registro de compras y ventas mensuales en software contable local e impresión física del libro diario.",
    skills: ["Software contable básico", "Excel"],
    schedule: "Part-time",
    modality: "Presencial"
  },
  {
    id: 91,
    title: "Ayudante en Granja y Alimentación",
    mype: "Finca El Porvenir",
    area: "Veterinaria",
    remunerated: true,
    pay: "S/ 80 por fin de semana",
    description: "Alimentar ganado ovino y porcino, limpieza de tolvas de granos y apoyo en vacunación menor.",
    skills: ["Fuerza física", "Trabajo en establo"],
    schedule: "Fines de semana",
    modality: "Presencial"
  },
  {
    id: 92,
    title: "Tutor de Álgebra Escolar",
    mype: "Centro Preuniversitario Exitus",
    area: "Educación",
    remunerated: true,
    pay: "S/ 18 por hora",
    description: "Apoyo en resolución de tareas de álgebra y trigonometría para alumnos de 3ro y 4to de secundaria.",
    skills: ["Pedagogía escolar", "Matemáticas"],
    schedule: "Tardes",
    modality: "Presencial"
  },
  {
    id: 93,
    title: "Ayudante de Repostería (Lunes a Jueves)",
    mype: "Pastelería Santa María",
    area: "Repostería",
    remunerated: true,
    pay: "S/ 500 al mes",
    description: "Apoyo en el pesado de mantequilla, azúcar, y batido de claras de huevo para tortas de bizcocho básicas.",
    skills: ["Higiene", "Pesado exacto", "Orden"],
    schedule: "Tardes, Lunes a Jueves",
    modality: "Presencial"
  },
  {
    id: 94,
    title: "Programador Frontend React (CSS)",
    mype: "Servicio Técnico Wilson",
    area: "Sistemas",
    remunerated: true,
    pay: "S/ 600 único",
    description: "Maquetar en React una vista de cotización de componentes de computadoras para tienda local de Wilson.",
    skills: ["React", "CSS Grid", "Forms"],
    schedule: "Flexible",
    modality: "Remoto"
  },
  {
    id: 95,
    title: "Auxiliar en Campañas Médicas UDH",
    mype: "Campañas Médicas UDH",
    area: "Enfermería",
    remunerated: false,
    pay: "Ad Honorem (Certificado)",
    description: "Apoyo en el registro de pacientes ancianos para toma de presión y descarte de diabetes en ferias locales.",
    skills: ["Empatía", "Llenado de planillas"],
    schedule: "Sábados mañana",
    modality: "Presencial"
  },
  {
    id: 96,
    title: "Trazador de Planos de Topografía CAD",
    mype: "Constructora e Inversiones",
    area: "Civil",
    remunerated: true,
    pay: "S/ 15 por plano digitalizado",
    description: "Delinear curvas de nivel a partir de coordenadas GPS provistas por el topógrafo a cargo.",
    skills: ["AutoCAD Civil 3D", "Curvas de nivel"],
    schedule: "Flexible",
    modality: "Remoto"
  },
  {
    id: 97,
    title: "Clasificador de Piezas en Taller",
    mype: "Metalmecánica El Inka",
    area: "Industrial",
    remunerated: true,
    pay: "S/ 550 al mes",
    description: "Clasificación de perfiles de acero cortados por medida, etiquetado manual e ingreso de cantidades en Excel.",
    skills: ["Uso de flexómetro", "Excel básico"],
    schedule: "Tardes",
    modality: "Presencial"
  },
  {
    id: 98,
    title: "Ilustrador de Diseños para Polos",
    mype: "Confecciones T-Shirt Art",
    area: "Diseño",
    remunerated: true,
    pay: "S/ 40 por diseño aprobado",
    description: "Crear ilustraciones en formato vector de caricaturas locales y frases típicas de Huánuco para serigraﬁar.",
    skills: ["Adobe Illustrator", "Creatividad"],
    schedule: "Flexible",
    modality: "Remoto"
  },
  {
    id: 99,
    title: "Auxiliar de Caja y Facturas",
    mype: "Cafetería La Parada",
    area: "Administración",
    remunerated: true,
    pay: "S/ 500 al mes",
    description: "Registro de facturas recibidas de proveedores de café y leche, arqueo de caja del turno tarde.",
    skills: ["Caja", "Arqueo", "Orden"],
    schedule: "Tardes",
    modality: "Presencial"
  },
  {
    id: 100,
    title: "Asistente de Campo Veterinario",
    mype: "Veterinaria Ganadera",
    area: "Veterinaria",
    remunerated: true,
    pay: "S/ 60 por salida de campo",
    description: "Sujeción e inyección intramuscular de antiparasitarios en terneros y cerdos de granjas periféricas.",
    skills: ["Sujeción de animales", "Inyección de fármacos"],
    schedule: "Sábados todo el día",
    modality: "Presencial"
  }
];
